repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/guy-av/flutter-format-pre-commit
    rev: "3f799e8fe06fdc62a12b0acbdffc6870ceb23750"
    hooks:
      - id: flutter-format
        files: lib/.*\.dart$ # Only format source files
        exclude: lib/src/avatar.dart # Exclude the avatar widget
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "4afcaa82fc368d40d486256bf4edba329bf667bb"
    hooks:
      - id: flutter-analyze
  # - repo: local
  #   hooks:
  #     - id: flutter-format
  #       name: flutter-format
  #       entry: .flutter-format.sh
  #       language: script
