// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzwnqiBgJ2Y3Zza5lts-9prXjLxyTa6A',
    appId: '1:216626847807:web:c7481ba68202971ea7988a',
    messagingSenderId: '216626847807',
    projectId: 'taminiapp',
    authDomain: 'taminiapp.firebaseapp.com',
    storageBucket: 'taminiapp.appspot.com',
    measurementId: 'G-VHTWPJY27Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ7cQoZ2JwAHCIUXdZR47K29aU7Hl-mxU',
    appId: '1:216626847807:android:8e158427a9c98c16a7988a',
    messagingSenderId: '216626847807',
    projectId: 'taminiapp',
    storageBucket: 'taminiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOW7wSJ2ImxkD9yq7qOuG9nDeFFC_8Hg',
    appId: '1:216626847807:ios:e480455b9d73657ca7988a',
    messagingSenderId: '216626847807',
    projectId: 'taminiapp',
    storageBucket: 'taminiapp.appspot.com',
    iosBundleId: 'com.example.taminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPOW7wSJ2ImxkD9yq7qOuG9nDeFFC_8Hg',
    appId: '1:216626847807:ios:19c7bff867db8892a7988a',
    messagingSenderId: '216626847807',
    projectId: 'taminiapp',
    storageBucket: 'taminiapp.appspot.com',
    iosBundleId: 'com.example.taminiApp.RunnerTests',
  );
}
